package main

import (
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl -s https://api.blockcypher.com/v1/eth/main

	resp, err := http.Get("https://api.blockcypher.com/v1/eth/main")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}

	log.Println(string(body))
}
